# Generated by Django 5.0.7 on 2024-09-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderinfo_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='tracking_code',
            new_name='post_tracking_code',
        ),
    ]
