version: '2.28.1'
services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=v$$kh8!kpsk%^b$$a!sm8mzo76a7q5%3v9dy&ychqoadysvp&3@wf645j*mrw%
      - DEBUG=0
      - MERCHANT_SECRET_KEY=zibal
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://bookstore_postgres_frz9_user:TrXiy6SFYKkRJknJLaauPiHGgiAXLWUN@dpg-cr53r4ij1k6c7392p8v0-a/bookstore_postgres_frz9
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_data: