# Generated by Django 5.0.7 on 2024-08-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_id_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
