# Generated by Django 5.0.7 on 2024-09-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_remove_book_category_book_primary_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='secondary_category',
            field=models.ManyToManyField(blank=True, related_name='sbooks', to='books.category'),
        ),
    ]
