# Generated by Django 5.0.7 on 2024-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_bookcategory'),
        ('users', '0003_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='owned_books',
            field=models.ManyToManyField(related_name='owners', to='books.book'),
        ),
    ]
