# Generated by Django 5.0.7 on 2024-09-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='total_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
