# Generated by Django 5.0.7 on 2024-09-01 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_bookcategory'),
        ('orders', '0007_orderedproductsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductsinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
