# Generated by Django 5.0.7 on 2024-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
