# Generated by Django 5.0.7 on 2024-08-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('author', 'Can read all books')]},
        ),
    ]
