# Generated by Django 5.0.7 on 2024-09-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderedproductsinfo_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name_plural': 'Order Info'},
        ),
    ]
