# Generated by Django 5.0.7 on 2024-09-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_tracking_code_orderinfo_post_tracking_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_id',
            new_name='tracking_code',
        ),
    ]
