# Generated by Django 5.0.7 on 2024-09-01 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_bookcategory'),
        ('orders', '0006_rename_order_id_orderinfo_tracking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProductsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderinfo')),
                ('product', models.ForeignKey(default='Unknown Product', on_delete=django.db.models.deletion.SET_DEFAULT, to='books.book')),
            ],
        ),
    ]
