# Generated by Django 5.0.7 on 2024-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderinfo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
