# Generated by Django 5.0.7 on 2024-09-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
